### ISSUE TITLE
Add a second pngoptimizer: pngquant

### ISSUE THREAD

**Issue by dennisvandehoef** [jtescher/image_optimizer#13]
When i run this command after using this gem, I am able to reduce the file size of png files even more.

`find . -name '*.png' | xargs pngquant --skip-if-larger --speed 1 --quality 100 --force --verbose --ext .png`

File sizes before:
![screen shot 2016-10-11 at 10 42 55](https://cloud.githubusercontent.com/assets/7486464/19264090/a2de1264-8f9f-11e6-82a7-78a113f4adff.png)

File sizes after:
![screen shot 2016-10-11 at 10 43 08](https://cloud.githubusercontent.com/assets/7486464/19264095/a9903218-8f9f-11e6-98d2-488bb9e4c05c.png)

**Comment by jtescher** [comment]
I'd be more than happy to review a PR to either add another optimizer or allow https://github.com/jtescher/image_optimizer/blob/master/lib/image_optimizer/gif_optimizer.rb#L24 to be configured. This is a very simple gem, shouldn't be too tricky.

**Comment by jtescher** [comment]
Fixed in #14
