### ISSUE TITLE
Is there any option to size the image?

### ISSUE THREAD

**Issue by Mahesh8** [jtescher/image_optimizer#15]
I would like to know if there is an option to resize an image. Also if you provide a list of all the available options, it would be helpful.

**Comment by jtescher** [comment]
So this can be used with carrirwave through the https://github.com/jtescher/carrierwave-imageoptimizer gem. Carrierwave can easily resize images for you.

Right now the options are listed in the README but if you want to re-organize the README to be more clear I'd look over it 👍

**Comment by jtescher** [comment]
Closing this for now, if you have other questions feel free to re-open or create a different issue
